# Generated by Django 5.1.3 on 2024-11-08 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_id', models.CharField(max_length=255)),
                ('music_name', models.CharField(max_length=255)),
                ('music_artist', models.CharField(max_length=255)),
                ('music_genre', models.CharField(max_length=255)),
            ],
        ),
    ]
