# Generated by Django 5.1.3 on 2024-11-08 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Musics',
            new_name='Music',
        ),
    ]
