# Generated by Django 5.1.3 on 2024-11-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0002_rename_musics_music'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='music_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
